### PR TITLE
반려견 리스트 이름 순 정렬해서 로드, 불필요 파일 삭제, Hilt 모듈 내 누락 어노테이션 추가

### PR DESCRIPTION
**Pull request by winteryy**
- 반려견 리스트 불러오는 기능 이름 순, orderBy 처리
- 불필요 파일들 삭제
- Hilt 모듈 내 누락 어노테이션 추가

resolved: #161

### CODE REVIEW

**Review by neoneoneo123 — APPROVED** [review]
확인했습니다!

**Review by juseonghyun — COMMENTED** [review]
PR내용 테스트를 해보고싶은데

<pre><code>
{ C:\Users\user\Desktop\ddaraogae\app\build\generated\hilt\component_sources\debug\com\nbcfinalteam2\ddaraogae\app\DdaraogaeApplication_HiltComponents.java:160: error: [Dagger/IncompatiblyScopedBindings] com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ViewModelC scoped with @dagger.hilt.android.scopes.ViewModelScoped may not reference bindings with different scopes:
  public abstract static class SingletonC implements DdaraogaeApplication_GeneratedInjector,
                         ^
      @Provides @Singleton android.net.ConnectivityManager com.nbcfinalteam2.ddaraogae.app.di.DeviceStateManagerModule.provideConnectivityManager(@dagger.hilt.android.qualifiers.ApplicationContext android.content.Context)
  
      @Provides @Singleton android.location.LocationManager com.nbcfinalteam2.ddaraogae.app.di.DeviceStateManagerModule.provideLocationManager(@dagger.hilt.android.qualifiers.ApplicationContext android.content.Context)
   [com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.SingletonC �� com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ActivityRetainedC �� com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ViewModelC]
}
</code></pre>

이렇게 오류가 떠서 테스트를 진행 못하고잇네용 ㅠㅠ

**Comment by winteryy** [comment]
> PR내용 테스트를 해보고싶은데
> 
> ```
> 
> { C:\Users\user\Desktop\ddaraogae\app\build\generated\hilt\component_sources\debug\com\nbcfinalteam2\ddaraogae\app\DdaraogaeApplication_HiltComponents.java:160: error: [Dagger/IncompatiblyScopedBindings] com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ViewModelC scoped with @dagger.hilt.android.scopes.ViewModelScoped may not reference bindings with different scopes:
>   public abstract static class SingletonC implements DdaraogaeApplication_GeneratedInjector,
>                          ^
>       @Provides @Singleton android.net.ConnectivityManager com.nbcfinalteam2.ddaraogae.app.di.DeviceStateManagerModule.provideConnectivityManager(@dagger.hilt.android.qualifiers.ApplicationContext android.content.Context)
>   
>       @Provides @Singleton android.location.LocationManager com.nbcfinalteam2.ddaraogae.app.di.DeviceStateManagerModule.provideLocationManager(@dagger.hilt.android.qualifiers.ApplicationContext android.content.Context)
>    [com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.SingletonC �� com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ActivityRetainedC �� com.nbcfinalteam2.ddaraogae.app.DdaraogaeApplication_HiltComponents.ViewModelC]
> }
> ```
> 
> 이렇게 오류가 떠서 테스트를 진행 못하고잇네용 ㅠㅠ

고민하다가 못 바꾼 부분이 그대로 올라갔었네요
수정해서 올렸습니다 감사합니다
@juseonghyun

**Review by juseonghyun — APPROVED** [review]
확인했습니다 수고하셨습니다!

**Pull request merged**
